### ISSUE TITLE
neo Object should have one Segment per reset

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker8#5]
Unlike PyNN7 In PyNN8 the Neo Object seperates data for different runs.

To be specific there should be one Segment per run.

**Comment by alan-stokes** [comment]
attempted to work with branches neo_pain

it is currently at a point where it will give you the seperate segemnts. but it also adds a lot more for multi calls to get_data. still needs looking into to get rid of these surplus segments. 

changes are in FEC (1 line to put buffer extractor in front of all algorithms) SPY for putting populations into inputs. SPY8 for most of the work. will try to solve on monyda morning. otherwise im doing energy

**Comment by alan-stokes** [comment]
works now. from the little tests ive done. is rather nasty code but works none the less. fixes are in these pull requests

https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/140
https://github.com/SpiNNakerManchester/sPyNNaker8/pull/8
https://github.com/SpiNNakerManchester/sPyNNaker/pull/320

**Comment by Christian-B** [comment]
Taking to Andrew Davis this is one segment per RESET not run.

**Comment by Christian-B** [comment]
BLOCKED by https://github.com/SpiNNakerManchester/sPyNNaker/issues/347

**Comment by alan-stokes** [comment]
unblocked by 
https://github.com/SpiNNakerManchester/sPyNNaker8/pull/35
https://github.com/SpiNNakerManchester/sPyNNaker/pull/357

**Comment by alan-stokes** [comment]
closed as fixed in master.
