### ISSUE TITLE
FromFileConnector instatiation error

### ISSUE THREAD

**Issue by kaenzign** [SpiNNakerManchester/sPyNNaker8#78]
I want to use the FromFileConnector to load synapse from a file, however, when instantiating the FromFileConnector I get the following error:
TypeError: Can't instantiate abstract class FromFileConnector with abstract methods get_reader

The other connector types are working.

**Comment by kaenzign** [comment]
Even though it runs now without error, it seems that the FileConnector still does not work properly. When using this connector I only get zero membrane potential values in subsequent layers, meaning no spikes get through. Maybe the weights of the synapses get overwritten by 0 or so somewhere.
At the moment I load the weights manually from my files into a list, und use then the FromListConnector, which works fine.

**Comment by alan-stokes** [comment]
HI kaenzign, 

You will need to give us more information than "it still doesn't work". If you look at the impl of the FromFileConnector found here: 
https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/neural_projections/connectors/from_file_connector.py

you will see that all it is doing is exactly the same as you yourself are doing. aka reading in the file and then handing the conn list to a FromListConnector. 

Maybe your not giving it the correct file format?
you may wish to read the definition of the FromFileConnector given by PyNN found here:
http://neuralensemble.org/docs/PyNN/reference/connectors.html

please give more details of your problem so that we can diagnose it.

**Comment by andrewgait** [comment]
In addition to what Alan's just said, you can also see an example (which does work) at https://github.com/SpiNNakerManchester/sPyNNaker8/blob/master/p8_integration_tests/test_from_file_connector/test_from_file_connector.py - I'd check what you're doing against this.

**Comment by alan-stokes** [comment]
going to close this issue, kaenzign can open it again if he finds a impl issue which we can fix.
